title: Jakub Zalas
subtitle: Agile Software Engineer

url: http://www.zalas.pl

google_analytics_tracking_id: 'UA-607315-1'
google_verify: 'mHEiONNL9DtmjWO7JCPw24xJ/FNQsnO8ekomLfropQg='

disqus:
    shortname: zalas-pl
